### ISSUE TITLE
[Feature Request] Allow Nulls for Optional Fields

### ISSUE THREAD

**Issue by skipjack** [typesense/typesense#266]
## Description

See initial discussion [here][1]. Rather than having to "clean" objects (i.e. delete any blank fields) it would be nice to be able to just pass `null` values for fields marked as `optional`. I guess cleaning them saves space and is worthwhile keeping around as an option, but both seem like valid use cases.

## Steps to reproduce

- Create a collection with optional fields.
- Upload some documents where those fields are `null` rather than non-existent.
- Observe the following error...

```
RequestMalformed [Error]: Request failed with HTTP code 400 | Server said: Field `title` must be a string.
```

## Expected Behavior

Optional fields would accept `null` values.

## Actual Behavior

The error noted above.

## Metadata

**Typsense Version**: 0.19.0
**OS**: MacOS 11.2.3

[1]: https://github.com/typesense/typesense/issues/91#issuecomment-833151382

**Comment by kishorenc** [comment]
This is addressed in this Docker RC build:`typesense/typesense:0.21.0.rc7` 

@skipjack Can you please try it out and confirm?

**Comment by skipjack** [comment]
Happy to try it out but I've been using the Mac binary not docker. Is that release available as a Mac binary? Any other significant breaking changes I should be aware of when jumping?

**Comment by kishorenc** [comment]
@skipjack Please use this Mac binary: https://dl.typesense.org/releases/0.21.0.rc8/typesense-server-0.21.0.rc8-darwin-amd64.tar.gz

There are no breaking changes, but we've now implemented prioritization of exact matches to address https://github.com/typesense/typesense/issues/191 and fixed some edge cases on fuzzy searching. Let me know if you find anything odd, but we have had other customers using this build so it should be fine.

**Comment by skipjack** [comment]
Tested and this appears to be working great! Though it does bring to mind some other questions...

- Seems typesense strips `null` fields from the response when searching?
- Is there a way to filter to find `null` fields?
- Where are they sorted? Tried `sort_by` with `asc` and `desc` on a field that I know has `null` for a number of objects but it didn't surface them. Are they being implicitly excluded on with `sort_by` or treated as `0` (in my case I have both negative and positive values so that would have pushed them to the middle I guess).

**Comment by kishorenc** [comment]
@skipjack 

Typesense just treats the `null` values as a field that is missing from the document. Otherwise we will have to use a special value to denote a `null` value, which might clash with a user provided value (this is especially tricky for numerical fields).  For the same reason, `null` values are also excluded from sorting since `null` doesn't really have a numerical value associated with it.

**Comment by kishorenc** [comment]
Shipped in `0.21.0` release.

**Comment by 0x80** [comment]
I'm passing the schema below to `client.collections().create()` , and my data contains `null`s for optional fields, but I still get this error on import:

> {
    code: 400,
    document: '{"id":"tMvdW0icNXMPJbengzVl1duT1qm2","lastName":null}',
    error: 'Field `lastName` must be a string.',
    success: false
  },

```ts 
const schema = {
      name: "users",
      fields: [
        {
          name: "id",
          type: "string",
        },
        {
          name: "firstName",
          type: "string",
          optional: true,
        },
        {
          name: "lastName",
          type: "string",
          optional: true,
        }
}
```

Am I missing something?
