### ISSUE TITLE
Return only facets that has more than 0 count 

### ISSUE THREAD

**Issue by Clasyc** [typesense/typesense#896]
Recently, the support for wildcard facet_by was merged (see https://github.com/typesense/typesense/pull/850). This feature is particularly useful when dealing with a large number of different filters that frequently change dynamically. When we have several hundred facets, using `facet_by: "*"` will return a considerable amount of unnecessary response data if the count on most of them is 0 (which is often the case when we make the search scope smaller by using a query or any other filter).

It would be beneficial to have a feature that allows us to exclude facets from the response if they contain no value. While this can be done on the client-side, having a server-side feature would be a valuable addition.

**Comment by kishorenc** [comment]
@Clasyc 

Thank you for reporting this. I agree that this will be a great usability addition. I think, by default, we should return zero counts at all in a dynamic facet scenario.

**Comment by Clasyc** [comment]
@happy-san hey, I see you made some progress on it, is there any chance to get this pull request. We are really waiting this feature.

**Comment by kishorenc** [comment]
@Clasyc I'll share a build later today. How do you deploy Typesense?

**Comment by Clasyc** [comment]
@kishorenc thanks! Changing the tag on swarm docker.

**Comment by kishorenc** [comment]
I've just published `typesense/typesense:0.25.0.rc12` Docker image.

**Comment by Clasyc** [comment]
It works as expected, thank you very much.

**Comment by Clasyc** [comment]
@kishorenc I'm failing to run docker-compose locally with `0.25.0.rc12`.
Not sure what happened, on initial testing it was working after the release few days ago. Now trying to run this container again I keep getting `SIGSEGV` error (docker container exited with 139).

If I switch back to `0.24.0` and run same docker-compose, it runs fine again:
```
d8dd60b530fd   typesense/typesense:0.24.0              "/opt/typesense-serv…"   2 minutes ago    Up About a minute               0.0.0.0:8108->8108/tcp                                                             typesense_1
```

Switching to `0.25.0.rc12`:
```
d267967b15d8   typesense/typesense:0.25.0.rc12         "/opt/typesense-serv…"   25 seconds ago   Exited (139) 21 seconds ago                                                                                       typesense_1
```

Docker logs are empty, container inspect status returns
```
...
 "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 139,
            "Error": "",
            "StartedAt": "2023-02-23T12:26:27.299662851Z",
            "FinishedAt": "2023-02-23T12:26:27.609660605Z"
        },
...
```

There is might a problem on my local setup somewhere and I'm just missing, but reverting to any previous tag it start working again.
Tried to delete volume, image, container and start fresh, didn't help. Any idea? is there anyway to debug the issue, because not sure where to look at.

**Comment by kishorenc** [comment]
Does the 0.25 RC build crash when you start it against an empty new directory? Or is the issue confined to loading your data or pointing to existing data directory?

**Comment by Clasyc** [comment]
Tried to run from empty dir (deleted my data volume), this is how docker-compose looks like:
```
  typesense:
    image: typesense/typesense:0.25.0.rc12
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
      - TYPESENSE_API_KEY=${TYPESENSE_NODE_API_KEY}
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data:rw
    networks:
      - local
```

and it still fails.

**Comment by Clasyc** [comment]
@kishorenc for example `0.25.0.rc9` also works just fine.

**Comment by kishorenc** [comment]
@kishorenc May I know what OS you are using? I just tried running the same Docker container on Mac (Intel) and it works. Do you use Linux or ARM Mac?

**Comment by Clasyc** [comment]
I have Linux, Ubuntu 18.04.5 (intel)
I'll try to update docker, maybe there is an issue with that

**Comment by Clasyc** [comment]
ok after upgrading docker, docker-engine to the latest version it is working now. Never had the issue like this before, sorry for wasting the time and thanks for your help

**Comment by kishorenc** [comment]
Non worries at all!
